"""Create UserProfile model with indexes

Revision ID: ead4fa15751d
Revises: 
Create Date: 2025-09-24 13:47:53.799045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ead4fa15751d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=6), nullable=False),
    sa.Column('region', sa.String(length=10), nullable=False),
    sa.Column('company', sa.String(length=10), nullable=True),
    sa.Column('bio', sa.String(length=128), nullable=True),
    sa.Column('hobbies', sa.String(length=10), nullable=True),
    sa.Column('interests', sa.Text(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_profile_name', 'user_profile', ['name'], unique=False)
    op.create_index('idx_user_profile_region', 'user_profile', ['region'], unique=False)
    op.create_index(op.f('ix_user_profile_id'), 'user_profile', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profile_id'), table_name='user_profile')
    op.drop_index('idx_user_profile_region', table_name='user_profile')
    op.drop_index('idx_user_profile_name', table_name='user_profile')
    op.drop_table('user_profile')
    # ### end Alembic commands ###